// a list of phrases
export default [
  "blue in the face",
  "ignorance is bliss",
  "knee jerk reaction",
  "a weight off my shoulders",
  "my Achilles heel",
  "cog in the machine",
  "hold your horses",
  "burning the midnight oil",
  "the world’s my oyster",
  "don’t muddy the waters",
  "upset the apple cart",
  "a bird in the hand",
  "a bite at the cherry",
  "a cast-iron stomach",
  "batten down the hatches",
  "don't beat a dead horse",
  "point of no return",
  "shiver me timbers",
  "tell it to the judge",
  "a chip on your shoulder",
  "back to the drawing board",
  "get your act together",
  "go with the flow",
  "it's raining cats and dogs",
  "kick the bucket",
  "let sleeping dogs lie",
  "make a mountain out of a molehill",
  "on the same page",
  "when pigs fly"
]