export default [
  "blue in the face",
  "ignorance is bliss",
  "knee jerk reaction",
  "a weight off my shoulders",
  "my Achilles heel",
  "cog in the machine",
  "hold your horses",
  "burning the midnight oil",
  "the world’s my oyster",
  "don’t muddy the waters",
  "upset the apple cart",
  "a bird in the hand",
  "a bite at the cherry",
  "a cast-iron stomach",
  "batten down the hatches",
  "don't beat a dead horse",
  "point of no return",
  "shiver me timbers",
  "tell it to the judge"
]